### ISSUE TITLE
🔨[refactor] 주문 취소, 부분취소 API 1개로 통합

### ISSUE THREAD

**Issue by jps091** [seokin23/for-work#189]
# 🔨 리팩토링이 필요한 부분 
기존 부분취소 취소 API 를 1개로 통합
# 리팩토링 작업 브런치

### ✅ refactoring TODO

- [ ] 기존 부분취소 취소 API 를 1개로 통합

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Refactored the OrderController, CancelService, and related DTOs to combine partial and full cancellation into a single API endpoint. Updated the cancel method in CancelService to handle both scenarios, and modified the OrderController to use the new unified cancellation approach.

You can review changes in this commit: https://github.com/lkilu6456546/jps091-for-work-189/commit/461dc2d3c02b4b982f5e30e2a69e9fde3c8f7ad0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
